### ISSUE TITLE
Replay attack prevention

### ISSUE THREAD

**Issue by joshuayabut** [zencashio/zen#12]
Opening this to track replay attack prevention efforts.

**Comment by joshuayabut** [comment]
Added d025556 which prevents tx replay attacks by altering the SIGHASH signing values. This commit will make new transaction have a completely different signature.

**Comment by joshuayabut** [comment]
Adding link to a replay attack prevention writeup (credit: @aayanl): https://medium.com/@ParisGuy/paris-smart-replay-protection-for-cryptocurrency-dfa6c241ec4c

**Comment by joshuayabut** [comment]
This might be a more elegant way to do replay prevention: https://github.com/luke-jr/bips/blob/bip-noreplay/bip-noreplay.mediawiki

**Comment by joshuayabut** [comment]
I've committed my current WIP. Here's one item so far that needs some consideration based on the BIP.

- The BIP allows for relative blockheights (like -200 for example) to be used with OP_CHECKBLOCKATHEIGHT. There isn't a good way to determine when a TX will be inserted into a block so looking up relative index's are troublesome. I recommend doing away with relative indexes altogether.

**Comment by joshuayabut** [comment]
The current implementation is ready for testing and code review https://github.com/zencashio/zen/commit/ea90598a13e9fb73adbb31c44357f3d5d9ffd8f4. 

Over the next few days I'll write some test suites for this, merge code to Zclassic, and then trial it on Zcl testnet.

**Comment by luke-jr** [comment]
Note OP_CHECKBLOCKATHEIGHT is not a final draft yet for Bitcoin, and is likely to change...
