### ISSUE TITLE
Forking Checklist

### ISSUE THREAD

**Issue by joshuayabut** [zencashio/zen#15]
Okay I'm going to list some of the things being done for the chainsplit so they don't get lost or overlooked.

## Zclassic
1. OP_CHECKBLOCKATHEIGHT BIP9 softfork implementation. **Mainnet & Testnet Pending Softfork Activation**

## Zen
1. Change network hash values. **ready**
2. OP_CHECKBLOCKATHEIGHT hardfork implementation. **ready**
3. Insert Core/DAO coinbase allocations. **ready**
4. Modify payment address prefix. **ready**

### Launch Procedures and Replay Protection
The Zen network will be bootstrapped using the Zclassic network at a specific block height and will also use a neo-genesis block manually built by Zen and set as a checkpoint. 

Since the network magic values are different this greatly reduces the risk of accidental transaction replays across both networks. _For DNS Seeds: In order to bootstrap the Zen network using the blk***.dat files from the Zclassic network the files must be modified to use the new Zen magic network value. Example of modifying magic value in block files:_
`sed 's/\x24\xe9\x27\x64/\x63\x71\x73\x68/g' blk00000.dat`

Additionally all Zen clients will submit new transactions using the new OP_CHECKBLOCKATHEIGHT opcode. Transactions without this opcode are still valid however and may be susceptible to malicious replay on the other network.

The OP_CHECKBLOCKATHEIGHT opcode inserts the block hash of the the 300th previous block into the pubkeysig portion of the transaction script. As a result of this, when a chainsplit occurs it will take 300 blocks for this replay prevention to be effective. 

### Accidental sends
The Zen chain split offers mitigations against accidental transactions across the Zclassic and Zen networks. Zen addresses are not compatible with Zclassic addresses and are prefixed with  "t4".

### Claiming Zen from Zclassic Private Keys
After the chainsplit occurs all users may import their private keys or copy and paste their wallet.dat into the new Zen/Eleos wallet in order to retrieve their pre-chainsplit Zen.

**Comment by joshuayabut** [comment]
Ran some tests on Zen testnet and transactions work just fine post-chainsplit. :D

**Comment by joshuayabut** [comment]
### WE MADE IT. 🥇

**Comment by aayanl** [comment]
woop!
