### ISSUE TITLE
Update tests for 't4' address prefix.

### ISSUE THREAD

**Issue by joshuayabut** [zencashio/zen#16]
The test suite will need to be updated to use the new 't4' address prefix and other changes implemented in chainparams.cpp.

Is there a way to build all of this automatically?

**Comment by aayanl** [comment]
sed :p

**Comment by joshuayabut** [comment]
I'm pretty sure this is it https://github.com/zencashio/zen/tree/master/contrib/testgen :0).

**Comment by joshuayabut** [comment]
I've updated contrib/testgen/gen_base58_test_vectors.py in the movrcx-wip-openssl branch to use the new prefixes and have also generated new test data.
