### ISSUE TITLE
"Founders reward" schedule is missing

### ISSUE THREAD

**Issue by sammy007** [zencashio/zen#24]
There is no clear "founders reward" schedule. Some mining software implements this on pool side and does not rely on GBT data, so post schedule somewhere, whitepaper is preferred. We need to know at what height what index of founders addresses array to use, etc.

Definitely I can take it from code, but there is just a stupid shim to return 0 index. I wonder if you are going to change it via hard fork later. Previous issue which I reported also highlight that multisig addresses in founders array are invalid according to base58 prefixes specified in chain params.

**Comment by joshuayabut** [comment]
The schedule is going to be unchanged the Zcash's implementation. The Core/DAO addresses for testnet have been merged into master. Mainnet will get merged in about 2-3 hours. Cheers!
