### ISSUE TITLE
TX loss mitigation: Update Base58 Prefixes

### ISSUE THREAD

**Issue by joshuayabut** [zencashio/zen#26]
In order to provide differentiation of address formats between the chainsplit it is desirable to change the base58 address of the newer chain.

o Starting at commit https://github.com/zencashio/zen/commit/4543107a65c6f21a4b6beaf81500c85c38a71610 create a new Github branch. 
o In the new branch cherry-pick commit https://github.com/zencashio/zen/commit/94df3b3535659030fe7de991d8935393d74dbdf1.

**Review/Continue existing transaction verification retrofitting**
 Update and continue retrofitting transaction signing validation functions. Using consensus.nChainsplitIndex located in chainparams.cpp update the base58 verification functions by instead of having a function check a single base58 prefix it will check against two base58 prefixes (old and new). 

It is not a requirement at this time to check blockheight against UTXO in order to determine which chain the transaction originated in but it is a nice to have.

There may be additional areas where code may need to be modified will likely include main.cpp. QA is necessary to determine if there are any other areas impacted by updating the base58 prefix.

## Example
**Original base58.cpp**
```
     bool fKnownVersion = vchVersion == params.Base58Prefix(CChainParams::PUBKEY_ADDRESS) ||
                         vchVersion == params.Base58Prefix(CChainParams::SCRIPT_ADDRESS);
      return fCorrectSize && fKnownVersion;
  }
```

**Retrofitted base58.cpp**
```
     bool fKnownVersion = vchVersion == params.Base58Prefix(CChainParams::PUBKEY_ADDRESS) ||
                          vchVersion == params.Base58Prefix(CChainParams::SCRIPT_ADDRESS) ||
                          vchVersion == params.Base58Prefix(CChainParams::PUBKEY_ADDRESS_OLD) ||
                          vchVersion == params.Base58Prefix(CChainParams::SCRIPT_ADDRESS_OLD);
      return fCorrectSize && fKnownVersion;
  }
```

**Comment by joshuayabut** [comment]
I've completed major work on cleaning up the OpenSSL implementation. It's missing x509 checks for now but that can be added later on. My new work will be pushed into the `fix-base58` branch for tracking purposes.

Current status as of bc7dadaccbaa3d0ec776bed279a1bb72e34a98dc:
Pre-Chainsplit Coinbase Reward - **works**
Post-Chainsplit Coinbase Reward - **works**
Pre-Chainsplit sendmany - _unknown_
Post-Chainsplit sendmany - _unknown_
Pre-Chainsplit z_sendmany - _unknown_
Post-Chainsplit z_sendmany - _unknown_

**Comment by joshuayabut** [comment]
Current tip of development is the master branch at commit 77822968f3ba41920f049dc0b6154f8294353cc0. At this commit transactions of all types **should** work.

The above transaction scenarios still need to be tested but I'm going to start QA'ing the OpenSSL implementation again.

**Comment by sennevb** [comment]
so i need to test z_sendmany?

**Comment by joshuayabut** [comment]
@sennevb Yes and sendmany too please.

**Comment by sennevb** [comment]
will do

**Comment by belmix** [comment]
branch master?

**Comment by belmix** [comment]
ok +1 test

**Comment by belmix** [comment]
opid-4c023f39-6b64-4032-9a38-e470235c2c01: z_sendmany finished (status=failed, error=Failed to sign transaction)

**Comment by belmix** [comment]
master branch

**Comment by belmix** [comment]
fix-base58 payments work?
I can check or not yet

**Comment by belmix** [comment]
It seems the payouts are working, but I can not synchronize up to 100% to include the transaction in the block

**Comment by belmix** [comment]
I will try reindex

**Comment by joshuayabut** [comment]
Current status as of 315a4b6 on master:
Pre-Chainsplit Coinbase Reward - **works**
Post-Chainsplit Coinbase Reward - **works**
Pre-Chainsplit sendmany - unknown
Post-Chainsplit sendmany - **works**
Pre-Chainsplit z_sendmany - unknown
Post-Chainsplit z_sendmany - **works**

**Comment by cronicc** [comment]
I can confirm that Post-Chainsplit z_sendmany works, shielded and unshielded my ZNT. I don't have any Pre-Chainsplit ZNT to test though.

**Comment by sennevb** [comment]
Nice work!

**Comment by joshuayabut** [comment]
Closing out since all the issues appear resolved.  🥇
