### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by githubee** [zencashio/zen#35]
### Describe the issue
Compilation on fresh Debian VPS fails

#### If so, please list the steps to reproduce below:
1. Setup packages, clone git repo
2. run build.sh
3. 

### Expected behaviour
Should compile

### Actual behaviour + errors
Compilation fails at:
[..]
Making all in src
make[1]: Entering directory '/root/zclassic/src'
make[2]: Entering directory '/root/zclassic/src'
/bin/bash ../libtool  --tag=CXX   --mode=compile /root/zclassic/depends/x86_64-unknown-linux-gnu/share/../native/bin/ccache g++ -m64 -DHAVE_CONFIG_H -I. -I../src/config  -I/root/zclassic/depends/x86_64-unknown-linux-gnu/include  -I./obj -DBUILD_BITCOIN_INTERNAL -I/root/zclassic/depends/x86_64-unknown-linux-gnu/share/../include/libsnark -I/root/zclassic/depends/x86_64-unknown-linux-gnu/share/../include/  -DHAVE_BUILD_INFO -D__STDC_FORMAT_MACROS  -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2  -std=c++11 -pipe -fPIC -O1 -fwrapv -fno-strict-aliasing -Werror -g  -Wformat -Wformat-security -Wstack-protector -fstack-protector-all -fPIE -MT crypto/libzcashconsensus_la-equihash.lo -MD -MP -MF crypto/.deps/libzcashconsensus_la-equihash.Tpo -c -o crypto/libzcashconsensus_la-equihash.lo `test -f 'crypto/equihash.cpp' || echo './'`crypto/equihash.cpp
libtool: compile:  /root/zclassic/depends/x86_64-unknown-linux-gnu/share/../native/bin/ccache g++ -m64 -DHAVE_CONFIG_H -I. -I../src/config -I/root/zclassic/depends/x86_64-unknown-linux-gnu/include -I./obj -DBUILD_BITCOIN_INTERNAL -I/root/zclassic/depends/x86_64-unknown-linux-gnu/share/../include/libsnark -I/root/zclassic/depends/x86_64-unknown-linux-gnu/share/../include/ -DHAVE_BUILD_INFO -D__STDC_FORMAT_MACROS -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -std=c++11 -pipe -fPIC -O1 -fwrapv -fno-strict-aliasing -Werror -g -Wformat -Wformat-security -Wstack-protector -fstack-protector-all -MT crypto/libzcashconsensus_la-equihash.lo -MD -MP -MF crypto/.deps/libzcashconsensus_la-equihash.Tpo -c crypto/equihash.cpp  -fPIC -DPIC -o crypto/.libs/libzcashconsensus_la-equihash.o
{standard input}: Assembler messages:
{standard input}:63306: Warning: end of file not at end of a line; newline inserted
{standard input}:64570: Error: unknown pseudo-op: `.lbb54570'
{standard input}: Error: open CFI at the end of file; missing .cfi_endproc directive
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.9/README.Bugs> for instructions.
Makefile:3915: recipe for target 'crypto/libzcashconsensus_la-equihash.lo' failed
make[2]: *** [crypto/libzcashconsensus_la-equihash.lo] Error 1
make[2]: Leaving directory '/root/zclassic/src'
Makefile:5165: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/root/zclassic/src'
Makefile:613: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
root@debian-test:~/zclassic#

### The version of Zen you were using:
unknown

### Machine specs:
- OS name + version: Debian 8.8 x64
- CPU: virtual
- RAM: 1GB
- Disk size: 40GB
- Disk Type (HD/SDD): SSD
- Linux kernel version (uname -a): 3.16.43-2
- Compiler version (gcc -version): 4.9.2-10

**Comment by aayanl** [comment]
Try increasing the amount of ram you have to at least 4gb

**Comment by githubee** [comment]
aayanl is right, increasing RAM fixed the issue (increased to 4GB).
