### ISSUE TITLE
Where can I find access to the eleos wallet?

### ISSUE THREAD

**Issue by kivo360** [zencashio/zen#37]
With the coming fork I found that eleos doesn't support zencash. Where can I access my coins? I didn't use bittrex and I'm nervous because I planned to take out half then stake 200 zencash tokens for nodes. 

This issue tracker is only for technical issues related to Zen.

General Zen questions and/or support requests and are best directed to the [Community Rocket.Chat](https://rocketchat.zdeveloper.org).

For reporting security vulnerabilities or for sensitive discussions with our security team, please contact @movrcx (@joshuayabut). 

### Describe the issue
Please provide a general summary of the issue you're experiencing

#### If so, please list the steps to reproduce below:
1. 
2. 
3. 

### Expected behaviour
Tell us what should happen

### Actual behaviour + errors
Tell us what happens instead including any noticable error output (any messages displayed on-screen when e.g. a crash occurred)

### The version of Zen you were using:
Run `zend --version` to find out

### Machine specs:
- OS name + version:
- CPU:
- RAM:
- Disk size:
- Disk Type (HD/SDD):
- Linux kernel version (uname -a):
- Compiler version (gcc -version):

### Any extra information that might be useful in the debugging process.
This includes the relevant contents of `~/.zen/debug.log`. You can paste raw text, attach the file directly in the issue or link to the text via a pastebin type site.
Please also include any non-standard things you did during compilation (extra flags, dependency version changes etc.) if applicable.

### Do you have a back up of `~/.zen` directory and/or take a VM snapshot?
- Backing up / making a copy of the `~/.zen` directory might help make the problem reproducible. Please redact appropriately.
- Taking a VM snapshot is really helpful for interactively testing fixes

**Comment by tarrenj** [comment]
https://github.com/zencashio/eleos

The wallet is still in early development and should **not** be considered stable.  Use at your own risk.

The recommended wallet is currently zen-cli, we have tested functionality in a linux VM on a windows host.

**Comment by aayanl** [comment]
Closing as unrelated to the zen codebase
