### ISSUE TITLE
Harden RPC and Network Transports

### ISSUE THREAD

**Issue by joshuayabut** [zencashio/zen#6]
At the present state Bitcoin and other cryptocurrency traffic is easily identifiable using IDS systems. Zen should be updated to push information over obfuscated transports instead. This will enable Zen to work in geographic areas that attempt to deny access to cryptocurrencies.

**Comment by aayanl** [comment]
The only problem is that with networks such as TOR and i2p is that they take a while to propagate. So if there's a really short block time, it can make an unstable blockchain even more unstable. Miners would choose to still use normal transports

**Comment by joshuayabut** [comment]
Routing through an overlay network isn't really the solution that I think would meet requirements. Both Tor and I2P traffic are pretty much easily identifiable in their current state. In some areas such as China and Syria; connecting to Tor without significant obfuscation is a red flag for active analysis.

As an example here are some of the capabilities that exist for monitoring Bitcoin network traffic [https://www.wireshark.org/docs/dfref/b/bitcoin.html](https://www.wireshark.org/docs/dfref/b/bitcoin.html). As it is, it's dangerous for nodes to communicate with each other because the traffic is sent in cleartext. At the very least transaction malleability attacks seem to be possible and the risk also increases if the blockchain is used as a datastore since specific requests for certain blocks (which would contain contraband data) can be easily monitored.

The best way to mitigate these flaws in my opinion is to enable TLS encryption for all nodes and to also break up nodes as trusted and untrusted depending on their configuration. Trusted nodes would require a valid TLS certificate (perhaps issued automatically by Lets Encrypt) and untrusted nodes would still use TLS but with a self-signed certificate (these nodes would be susceptible to man-in-the-middle attacks). 

On top of the encryption the traffic may be further obfuscated using a Tor-style pluggable transport, [obfs4](https://trac.torproject.org/projects/tor/wiki/doc/PluggableTransports/Obfs4Evaluation) I think would be a good choice.

**Comment by aayanl** [comment]
So kinda like [bip 151](https://github.com/bitcoin/bips/blob/master/bip-0151.mediawiki)?

**Comment by joshuayabut** [comment]
Sort of but not really... In that BIP a man-in-the-middle attacker could refuse to relay those encinit messages and it seems like the network would just fallback to no encryption. So it's not really good for use in adversarial environments. Additionally the encinit message by itself is evidence that Bitcoin network activity is occurring.

The encryption suite is an interesting choice too I would think AES would be a better choice since its suitable to secure data at the TS-level and above.
