### ISSUE TITLE
 Network Magic Start Value

### ISSUE THREAD

**Issue by mountaindrifter** [zencashio/zen#8]
A few months ago I had brought up changing the Network Magic Start Value (pchMessageStart) in Zclassic. It looks like Zen is using the same as ZCL and ZEC. It seems that while it is not urgent, it may be a good idea to make this unique before the launch.

main CMainParams
[chainparams.cpp#L54](https://github.com/zencashio/zen/blob/master/src/chainparams.cpp#L54 )

test CTestNetParams
https://github.com/zencashio/zen/blob/master/src/chainparams.cpp#L203

Regression CRegTestParams
https://github.com/zencashio/zen/blob/master/src/chainparams.cpp#L285

The actual value shouldn't matter, just needs to be unique from other bitcoin type networks. In the bitcoin documents it says their value was chosen at random as it was an unlikely value to occur naturally. 

Maybe something like this mor main: `63 61 73 68` 
(little secret message in there :1st_place_medal: ). 

Maybe it should be something more random? Suppose you could just use whatever this generates:
 ```echo "#$(openssl rand -hex 4)"```

**Comment by mountaindrifter** [comment]
created a quick PR #9 in case you are busy, but feel free to use whatever values you like

**Comment by mountaindrifter** [comment]
lets also decide on the main/test connection & rpc ports as well as the PROTCOL_VERSION while we are at it

**Comment by joshuayabut** [comment]
Ports are updated. I don't think there needs to be any adjustment to the PROTOCOL_VERSION though?

**Comment by joshuayabut** [comment]
Merged.
